---
title: Thibault Flowchart - Chapter 34
config:
  layout: dagre
  flowchart:
    htmlLabels: false
---
flowchart LR
	%% Nodes
	B2_T03_C01["Circle 1"]
	B2_T03_C02["Circle 2"]
	B2_T03_C03["Circle 3"]
	B2_T03_C04["Circle 4"]
	B2_T03_C05["Circle 5"]
	B2_T03_C06["Circle 6"]
	B2_T03_C07["Circle 7"]
	B2_T03_C08["Circle 8"]
	B2_T03_C09["Circle 9"]
	B2_T03_C10["Circle 10"]
	B2_T03_C11["Circle 11"]
	B2_T03_C12["Circle 12"]

	%% Edges
	B2_T03_C01 --> B2_T03_C02
	B2_T03_C02 --> B2_T03_C03
	B2_T03_C02 --> B2_T03_C04
	B2_T03_C02 --> B2_T03_C05
	B2_T03_C05 --> B2_T03_C06
	B2_T03_C02 --> B2_T03_C07
	B2_T03_C08 --> B2_T03_C09
	B2_T03_C09 --> B2_T03_C10
