---
title: Thibault Flowchart - Chapter 5
config:
  layout: dagre
  flowchart:
    htmlLabels: false
---
flowchart LR
	%% Nodes
	T05_C01["Circle 1"]
	T05_C02["Circle 2"]
	T05_C03["Circle 3"]
	T05_C04["Circle 4"]
	T05_C05["Circle 5"]
	T05_C06["Circle 6"]
	T05_C07["Circle 7"]
	T05_C08["Circle 8"]
	T05_C09["Circle 9"]
	T05_C10["Circle 10"]
	T05_C11["Circle 11"]
	T05_C12["Circle 12"]
	T05_C13["Circle 13"]

	%% Edges
	T05_C01 --> T05_C02
	T05_C01 --> T05_C03
	T05_C04 --> T05_C05
	T05_C06 --> T05_C07
	T05_C07 --> T05_C08
	T05_C09 --> T05_C10
	T05_C11 --> T05_C12
	T05_C12 --> T05_C13